#Swagger docs:
#https://swagger.io/docs/specification/basic-structure/
openapi: 3.0.0
info:
  title: Print contract.
  description: Here are the methoods of the print contract
  version: 0.0.1
  contact:
    email: ac.lopez@uniandes.edu.co
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: /api
    description: API server
paths:
  /print:
    get:
      summary: Return prints's
      description: Get all the prints
      responses:
        '200':    # status code
          description: Some description
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
    post:
      summary: Add a new quotation to blockchain
      description: Create a print
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
            example:
              moneyPrice: 100
              materialPrice: 20
              timePrice: 200
              docName: trabajoFinal
              date: 20/03/2021
              userId: 123123
              printerId: 8372
      responses:
        '200':    # status code
          description: Respose
          content:
            application/json:
              schema:
                type: object
  /{id}:
    get:
      summary: Returns a print by ID
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the print to return.
          schema:
            type: integer
            format: int64
            minimum: 1
          example:
            10
      responses:
          '200':    # status code
            description: The print
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    text:
                      type: string
                example:
                  moneyPrice: 100
                  materialPrice: 20
                  timePrice: 200
                  docName: trabajoFinal
                  date: 20/03/2021
                  userId: 123123
                  printerId: 8372

