#
# SPDX-License-Identifier: Apache-2.0
#

# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:
  # ---------------------------------------------------------------------------
  # PrinterOrg
  # ---------------------------------------------------------------------------
  - Name: PrinterOrg
    Domain: printerorg.impreAndes.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 0
