#Swagger docs:
#https://swagger.io/docs/specification/basic-structure/
openapi: 3.0.0
info:
  title: Quote contract.
  description: Here are the methoods of the quote contract
  version: 0.0.1
  contact:
    email: ac.lopez@uniandes.edu.co
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: /api
    description: API server
paths:
  /all:
    get:
      summary: Return all the elements in blockchain
      description: Get all the elements in blockchain
      responses:
        '200':    # status code
          description: Some description
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
  /quote:
    get:
      summary: Return quote's
      description: Get all the quotes
      responses:
        '200':    # status code
          description: Some description
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
    post:
      summary: Add a new quotation to blockchain
      description: Create a quote
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
            example:
              price: 11241.88
              id: "2e8c7fd4-efdb-45e8-96f6-c662ae8884f5" 
              deliveryDate: "2021-06-17T20:50:11.000Z"
              clientId: "572487b8-ed2b-4ee8-9f3f-efa067a65835"
              printerId: "0f7d2211-c84e-482b-91f2-7b019d73ea07"
              manufacturerId: "6277deac-cce0-4fc2-a7eb-e5145153e382"
              catalogItemId: "170f003d-1481-428c-b078-e07ccf9cbf0f"
              printSettingsIds: ["8664044d-503d-4a13-8e36-b1abe5146387","581d3fed-ced8-43ad-9dde-25ed6fc20151","c4425f39-b6a5-404c-b4ff-966b51b5fd43","fcf0300d-ea97-49fa-87c2-805aea774122","e3abfc9a-8ade-4451-84ef-b8f6c09ec0e6","5f9710b8-2420-48ca-9d95-b9b51ebd21c9","0ed45481-8671-4d25-af35-2a9847051b18","2e56f0ff-bca4-49db-9d51-a348425e08ab"]
              signature: "0xa4c631d5f247538cdb68ad72403f5e602817b060bf45a4ef9dbf28224af296505cf5c5f6e33ac001112913668c71586dc601c7ed93170f3c80cc9be5bd28968c1b"
      responses:
        '200':    # status code
          description: Respose
          content:
            application/json:
              schema:
                type: object
  /quote/{id}:
    get:
      summary: Returns a quote by ID
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the quote to return.
          schema:
          example:
            1827172y2ws2w2
      responses:
          '200':    # status code
            description: The quote
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    text:
                      type: string
                example:
                  price: 100
                  id: "1827172y2ws2w2" 
                  deliveryDate: 20/03/2021
                  clientId: ac.lopez
                  printerId: 8372
                  manufacturerId: "rer2323342"

