#Swagger docs:
#https://swagger.io/docs/specification/basic-structure/
openapi: 3.0.0
info:
  title: Print Money contract.
  description: Here are the methoods of the print money contract
  version: 0.0.1
  contact:
    email: ac.lopez@uniandes.edu.co
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: /api
    description: API server
paths:
  /deliver:
    put:
      summary: Update a print by ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
            example:
              id: "dwwedwe323ede"
              quotationId: "1827172y2ws2w2"
      responses:
          '200':    # status code
            description: 
            content:
              application/json:
                schema:
                  type: object
  /printFinish:
    get:
      summary: Return print's
      description: Get all the prints finish
      responses:
        '200':    # status code
          description: Some description
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
    put:
      summary: Update a print by ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
            example:
              id: "dwwedwe323ede"
              quotationId: "1827172y2ws2w2"
      responses:
          '200':    # status code
            description: 
            content:
              application/json:
                schema:
                  type: object
  /printFinish/{id}:
    get:
      summary: Returns a print finish by ID
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the print finish to return.
          schema:
          example:
            1827172y2ws2w2
      responses:
          '200':    # status code
            description: The print finish
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    text:
                      type: string
                example:
                  price: 100
                  id: "1827172y2ws2w2" 
                  deliveryDate: 20/03/2021
                  clientId: ac.lopez
                  printerId: 8372
                  manufacturerId: "rer2323342"
