#Swagger docs:
#https://swagger.io/docs/specification/basic-structure/
openapi: 3.0.0
info:
  title: Print Money contract.
  description: Here are the methoods of the print money contract
  version: 0.0.1
  contact:
    email: ac.lopez@uniandes.edu.co
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: /api
    description: API server
paths:
  /deliver:
    put:
      summary: Update a deliver by ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
            example:
              id: "dwwedwe323ede"
              order: {
                id: "8372",
                quotationId: "1827172y2ws2w2"
              }
              signature: "W8VO/naC7b5msluGMvWsX5XScOvajAYWTKn2l6dSsfWQmC5S/Ze7JddljSJEIJTM7QmGjsF8ls958VPNwOhdKuAlUvPmp0T1rsq/rS4SEaCcdV8eygXKPJNfjvLc71WsHt2We8wYwlfAJr/pQyhG3lwZ182LwPJtA3rE1ob1E6wrTpdTZ78i/g8Z2LS3DRiD35IqeXjq/uFAUtnE1v9O29LHqrHUN1xnbYGp8gu2C3aXXBGFMi8ibJzHSU5noZBgzGc5bLGO+sPIQMTLBHa+/1FO8QUqx2Ffs/tAgaX08L1jWvt7dYDgzuGovEeBvyk0WEeNqaT/HpfQNgpBSeZESg=="
      responses:
          '200':    # status code
            description: 
            content:
              application/json:
                schema:
                  type: object
    get:
        summary: Return deliver's
        description: Get all the prints delivered
        responses:
          '200':    # status code
            description: Some description
            content:
              application/json:
                schema:
                  type: array
                  items:
                    type: object
  /printFinish:
    get:
      summary: Return print's
      description: Get all the prints finish
      responses:
        '200':    # status code
          description: Some description
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
    put:
      summary: Update a order finish by ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
            example:
              id: "dwwedwe323ede"
              order: {
                id: "8372",
                quotationId: "1827172y2ws2w2"
              }
              signature: "W8VO/naC7b5msluGMvWsX5XScOvajAYWTKn2l6dSsfWQmC5S/Ze7JddljSJEIJTM7QmGjsF8ls958VPNwOhdKuAlUvPmp0T1rsq/rS4SEaCcdV8eygXKPJNfjvLc71WsHt2We8wYwlfAJr/pQyhG3lwZ182LwPJtA3rE1ob1E6wrTpdTZ78i/g8Z2LS3DRiD35IqeXjq/uFAUtnE1v9O29LHqrHUN1xnbYGp8gu2C3aXXBGFMi8ibJzHSU5noZBgzGc5bLGO+sPIQMTLBHa+/1FO8QUqx2Ffs/tAgaX08L1jWvt7dYDgzuGovEeBvyk0WEeNqaT/HpfQNgpBSeZESg=="
      responses:
          '200':    # status code
            description: 
            content:
              application/json:
                schema:
                  type: object
  /printFinish/{id}:
    get:
      summary: Returns a print finish by ID
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the print finish to return.
          schema:
          example:
            1827172y2ws2w2
      responses:
          '200':    # status code
            description: The print finish
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    text:
                      type: string
                example:
                  price: 100
                  id: "1827172y2ws2w2" 
                  deliveryDate: 20/03/2021
                  clientId: ac.lopez
                  printerId: 8372
                  manufacturerId: "rer2323342"
    /deliver/{id}:
      get:
        summary: Returns a print delivered by ID
        parameters:
          - name: id
            in: path
            required: true
            description: The ID of the print delivered to return.
            schema:
            example:
              1827172y2ws2w2
        responses:
            '200':    # status code
              description: The print delivered
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      text:
                        type: string
                  example:
                    price: 100
                    id: "1827172y2ws2w2" 
                    deliveryDate: 20/03/2021
                    clientId: ac.lopez
                    printerId: 8372
                    manufacturerId: "rer2323342"
