#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

networks:
  trade:

services:
  impreAndesUsers_rest:
    container_name: impreAndesUsers_rest
    image: impreAndesUsers-rest:latest
    environment:
      - CONFIG_PATH=/config
    working_dir: /usr/src/app
    volumes:
        - ../:/config
    ports:
      - "4000:4000"
    networks:
      - trade

  printer_rest:
    container_name: printer_rest
    image: printer-rest:latest
    environment:
      - CONFIG_PATH=/config
    working_dir: /usr/src/app
    volumes:
        - ../:/config
    ports:
      - "5000:5000"
    networks:
      - trade

  regulator_rest:
    container_name: regulator_rest
    image: regulator-rest:latest
    environment:
      - CONFIG_PATH=/config
    working_dir: /usr/src/app
    volumes:
        - ../:/config
    ports:
      - "6000:6000"
    networks:
      - trade

  senecas_rest:
    container_name: senecas_rest
    image: senecas-rest:latest
    environment:
      - CONFIG_PATH=/config
    working_dir: /usr/src/app
    volumes:
        - ../:/config
    ports:
      - "7000:7000"
    networks:
      - trade